export const AUTH = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_AUTH: 'GET_AUTH'
}

export const SYSTEM = {
  INFO: 'INFO'
}

export const ACCOUNT = {
  GET_ALL_ACCOUNTS: 'GET_ALL_ACCOUNTS',
  GET_ACCOUNT_PROFILE: 'GET_DETAIL_ACCOUNT',
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR'
}
