export const AUTH = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_AUTH: 'GET_AUTH',
  USER_GUARD: 'ADMIN_GURAD'
}

export const SYSTEM = {
  INFO: 'INFO'
}

export const ACCOUNT = {
  GET_ALL_ACCOUNTS: 'GET_ALL_ACCOUNTS',
  GET_ACCOUNT_PROFILE: 'GET_DETAIL_ACCOUNT',
  UDATE_ACCOUNT: 'EDIT_ACCOUNT',
  UPDATE_PROFILE_ACCOUNT: 'EDIT_PROFILE',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR'
}

export const AIR_CRAFT = {
  GET_ALL_AIR_CRAFT: 'GET_ALL_AIR_CRAFT',
  GET_AIR_CRAFT_DETAIL: 'GET_AIR_CRAFT_DETAIL',
  CREATE_AIR_CRAFT: 'CREATE_AIR_CRAFT',
  DELETE_AIR_CRAFT: 'DELETE_AIR_CRAFT',
  AIR_CRAFT_ERROR: 'AIR_CRAFT_ERROR',
  UPDATE_CRAFT: 'UPDATE_CRAFT'
}

export const CRAFT_TYPE = {
  GET_ALL_CRAFT_TYPE: 'GET_ALL_CRAFT_TYPE',
  GET_TYPE_DETAIL: 'GET_TYPE_DETAIL',
  CREATE_CRAFT_TYPE: 'CREATE_CRAFT_TYPE',
  CREATE_SEAT_BY_CLASS: 'CREATE_SEAT_BY_CLASS',
  CRAFT_TYPE_ERROR: 'CRAFT_TYPE_ERROR',
}
export const AIRPORT = {
  GET_ALL_AIRPORT: 'GET_ALL_AIRPORT',
  AIRPORT_ERROR: 'AIRPORT_ERROR'
}


export const FLIGHT = {
  GET_ALL_FLIGHT: 'GET_ALL_FLIGHT',
  CREATE_FLIGHT: 'CREATE_FLIGHT',
  UPDATE_FLIGHT: 'UPDATE_FLIGHT',
  DELETE_FLIGHT: 'DELETE_FLIGHT',
  FLIGHT_ERROR: 'FLIGHT_ERROR'
}

export const AIRWAY = {
  GET_ALL_AIRWAY: 'GET_ALL_AIRWAY',
  AIRWAY_ERROR: 'AIRWAY_ERROR'
}

export const TICKET = {
  GET_ALL_TICKET: 'GET_ALL_TICKET',
  TICKET_ERROR: 'TICKET_ERROR'
}

