export const AUTH = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_AUTH: 'GET_AUTH'
}

export const SYSTEM = {
  INFO: 'INFO'
}

export const ACCOUNT = {
  GET_ALL_ACCOUNTS: 'GET_ALL_ACCOUNTS',
  GET_ACCOUNT_PROFILE: 'GET_DETAIL_ACCOUNT',
  UPDATE_PROFILE_ACCOUNT: 'EDIT_ACCOUNT',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR'
}

export const AIR_CRAFT = {
  GET_ALL_AIR_CRAFT: 'GET_ALL_AIR_CRAFT',
  GET_AIR_CRAFT_DETAIL: 'GET_AIR_CRAFT_DETAIL',
  AIR_CRAFT_ERROR: 'AIR_CRAFT_ERROR',
}
