
export const LOCAL_STORAGE = {
  TOKEN: 'TOKEN',
  USER: 'USER',
  SIDEBAR_COLLAPSED: 'SIDEBAR_COLLAPSED',
  LOCK_SCREEN: 'LOCK_SCREEN',
  STEP_1: 'STEP_1',
  STEP_2: 'STEP_2',
  STEP_3: 'STEP_3',
  STEP_4: 'STEP_4'
}
